#! /bin/sh

cur_brightness=$(/usr/lib/gnome-settings-daemon/gsd-backlight-helper --get-brightness)
sudo intel_reg write 0x00061254 0x60FF6001
sudo /usr/lib/gnome-settings-daemon/gsd-backlight-helper --set-brightness "$cur_brightness"
exit 0
